BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[DeductionModel] ALTER COLUMN [DED_NO] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[DeductionModel] ALTER COLUMN [DEDCAL] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[DeductionModel] ALTER COLUMN [deddifcal] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[DeductionModel] ALTER COLUMN [DEDBAL] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[DeductionModel] ALTER COLUMN [dedprevdifcal] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
