BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[EmployeeModel] (
    [id] INT NOT NULL IDENTITY(1,1),
    [EMP_NO] NVARCHAR(1000) NOT NULL,
    [namefull_emp_name] NVARCHAR(1000) NOT NULL,
    [YEAR_NO] NVARCHAR(1000) NOT NULL,
    [MONTH_NO] NVARCHAR(1000) NOT NULL,
    [CIVIL_NO] NVARCHAR(1000) NOT NULL,
    [ACTIVE] NVARCHAR(1000) NOT NULL,
    [cal_centre_code] NVARCHAR(1000) NOT NULL,
    [INCRDIF] NVARCHAR(1000) NOT NULL,
    [CALSAL] NVARCHAR(1000) NOT NULL,
    [PAIDSAL] NVARCHAR(1000) NOT NULL,
    [sgrade] NVARCHAR(1000) NOT NULL,
    [GradeStep] NVARCHAR(1000) NOT NULL,
    [GRSDED] NVARCHAR(1000) NOT NULL,
    [LSTRND] NVARCHAR(1000) NOT NULL,
    [NXTRND] NVARCHAR(1000) NOT NULL,
    [GRSALW] NVARCHAR(1000) NOT NULL,
    [abs_days] NVARCHAR(1000) NOT NULL,
    [JobGrade] NVARCHAR(1000) NOT NULL,
    [CERT_NM] NVARCHAR(1000) NOT NULL,
    [JOB_NM] NVARCHAR(1000) NOT NULL,
    [ORGSAL] NVARCHAR(1000),
    [POST_NM] NVARCHAR(1000),
    CONSTRAINT [EmployeeModel_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
